# Generated by Django 5.2 on 2025-05-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoquemodel',
            old_name='completo',
            new_name='em_estoque',
        ),
    ]
